ECommerceMVC/Controllers/HangHoaController.cs
using ECommerceMVC.Data;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceMVC.Controllers
{
    public class HangHoaController : Controller
    {
        private readonly Hshop2023Context db;

        //Đầu tiên muốn làm việc với CSDL thì nhúng vô cái CSDL
        public HangHoaController(Hshop2023Context context)
        {
            db = context;
        }

        public IActionResult Index(int? loai)
        {
            //Lấy hết tất cả hàng hoá ra
            var hangHoas = db.HangHoas.AsQueryable();
            //Kiểm tra xem cột loại này có valus hay không
            if(loai.HasValue)
            {
                //Kiểm tra xem cái cột mã loại có bằng với mã loại ngta truyền vô không
                hangHoas = hangHoas.Where(p => p.MaLoai == loai.Value);
            }    

            return View();
        }
    }
}

ECommerceMVC/Views/Shared/Components/MenuLoai/Default.cshtml
@model IEnumerable<ECommerceMVC.ViewModels.MenuLoaiVM>

<div class="col-lg-12">
    <div class="mb-3">
        <h4>Danh mục</h4>
        <ul class="list-unstyled fruite-categorie">
            @foreach (var item in Model)
            {
                <li>
                    <div class="d-flex justify-content-between fruite-name">
                    <a asp-controller="HangHoa" asp-action="Index" asp-route-loai="@item.MaLoai">
                        <i class="fas fa-apple-alt me-2"></i>@item.TenLoai
                    </a>
                    <span>@item.SoLuong</span>
                </div>
            </li>
            }
        </ul>
    </div>
</div>